Repository sabuto/hassio-telegraf, pull requests merged in 2020-02, with the labels that each got.

#18 feature: updated readme, config and run
  README.md
  telegraf/config.json
  telegraf/run.sh
Labels: feature

#19 chore: move to GitHub workflow
  .github/workflows/build.yml
  .github/workflows/tag.yml
  .travis.yml
  build.sh
  dist.sh
Labels: chore

#22 enhancement: install smartmontools from backports repository
  telegraf/Dockerfile
Labels: enhancement

#21 feature: add support for scrapping thermal subsystem
  README.md
  telegraf/config.json
  telegraf/run.sh
Labels: feature

#25 feature: add use custom conf feature
  .idea/deployment.xml
  .idea/workspace.xml
  README.md
  telegraf/Dockerfile
  telegraf/build.json
  telegraf/config.json
  telegraf/run.sh
Labels: feature
